### PR TITLE
dep: update awsV1Version to 2.0.1

### PR DESCRIPTION
**Pull request by sepulworld**
Issue #384 I provided notes in there. Opening MR to see github workflow results. Will test locally as well.

### CODE REVIEW

**Comment by sepulworld** [comment]
Running build and test in my forked repo. https://github.com/sepulworld/java-dynamic-sqs-listener/actions/runs/3432068431/jobs/5721602891

https://github.com/awslabs/amazon-sqs-java-messaging-lib --- 1.0.8 uses an older 1.11 version of the Java AWS SDK v1. looks like they have 2.0.1 out which uses latest Java AWS SDK v2 💯  Let's give that a shot. It should support OpenID Connect!

**Comment by GhadgePrachi** [comment]
thanks @sepulworld for raising this pull request!
It will be good to update the aws sdk to a recent version so we get to use features like AWS OpenID Connect.

**Comment by JaidenAshmore** [comment]
This library already uses the Aws SDK V2, see the version being set here: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/5.x/gradle.properties#L5  and utilised here: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/5.x/api/build.gradle.kts#L6

The AWS V1 was just used for an ability to compare different SQS Libraries.

**Comment by sepulworld** [comment]
Thanks @JaidenAshmore! Yes I was able to pull that together. Unfortunately it doesn't seem to be using the AWS STS lib during the defaultClient creation. This means the 3rd option in the default credentials chain is skipped. That is the issue I am seeing now

**Comment by sepulworld** [comment]
I opened a separate branch to start testing how the defaultClient is created

**Pull request closed without merging**
